"""Database models for Supabase integration."""

from datetime import datetime
from typing import List, Optional, Any, Dict
from uuid import UUID, uuid4
from pydantic import BaseModel, Field
from enum import Enum


class Role(str, Enum):
    """Message role enum."""
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class ChartType(str, Enum):
    """Chart type enum."""
    LINE = "line"
    BAR = "bar"
    PIE = "pie"
    CONTROL_CHART = "control_chart"
    RUN_CHART = "run_chart"
    X_BAR_S = "x_bar_s"
    I_CHART = "i_chart"
    P_CHART = "p_chart"
    C_CHART = "c_chart"
    U_CHART = "u_chart"
    T_CHART = "t_chart"
    NONE = "none"


class User(BaseModel):
    """User model."""
    id: UUID = Field(default_factory=uuid4)
    auth_user_id: UUID
    email: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    last_seen_at: Optional[datetime] = None


class Thread(BaseModel):
    """Thread model."""
    id: UUID = Field(default_factory=uuid4)
    user_id: UUID
    title: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class Message(BaseModel):
    """Message model."""
    id: UUID = Field(default_factory=uuid4)
    thread_id: UUID
    user_id: UUID
    role: Role
    content: Dict[str, Any]  # JSON content
    uploaded_file_names: List[str] = Field(default_factory=list)
    uploaded_file_ids: List[str] = Field(default_factory=list)
    metadata: Optional[Dict[str, Any]] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Analytics(BaseModel):
    """Analytics model."""
    id: UUID = Field(default_factory=uuid4)
    message_id: UUID
    latency_ms: int
    input_tokens: int
    output_tokens: int
    cost_usd: float = Field(ge=0, decimal_places=6)
    chart_type: ChartType
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Feedback(BaseModel):
    """Feedback model."""
    id: UUID = Field(default_factory=uuid4)
    message_id: UUID
    user_id: UUID
    success: bool
    reason: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


# Request/Response models for API
class ChatRequest(BaseModel):
    """Chat request model."""
    user_message: str
    thread_id: Optional[UUID] = None
    user_id: UUID
    previous_response_id: Optional[str] = None
    system_prompt: Optional[str] = None
    file_names: List[str] = Field(default_factory=list)
    stream: bool = False


class DownloadableFile(BaseModel):
    """Downloadable file model for files generated by code interpreter."""
    filename: str
    data: str  # Base64 encoded file content
    mime_type: str
    sandbox_path: str


class AnalyticsData(BaseModel):
    """Analytics data for background processing."""
    message_id: UUID
    latency_ms: int
    input_tokens: int
    output_tokens: int
    cost_usd: float
    chart_type: ChartType
    thread_id: UUID
    user_id: UUID
    user_message: str
    assistant_response: Dict[str, Any] | Any
    file_names: List[str]
    downloadable_files: List[DownloadableFile] = Field(default_factory=list)
