-- Migration: Add downloadable_files column to messages table
-- This stores file data (base64) for files generated by code interpreter
-- so they persist and are available after page refresh

ALTER TABLE public.messages 
ADD COLUMN IF NOT EXISTS downloadable_files jsonb DEFAULT '[]'::jsonb;

-- Add comment for documentation
COMMENT ON COLUMN public.messages.downloadable_files IS 'Stores downloadable files (CSV, Excel, etc.) generated by code interpreter as base64 data. Structure: [{filename, data, mime_type, sandbox_path}]';

